### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by OriginersMc** [zPirroZ3007/UUIDSpoofFix#1]
Hi!

I add your plugin to my server, but users can join as my nickname changing som words.

Example, if my name is CalebCreep, hackers, use nick CAlebCreep and plugin don't kick "CAlebCreep".

Solution?

**Comment by zPirroZ3007** [comment]
This is not UUID Spoofing related. You must setup AuthMe properly, also add BlockThatName.

Kindest Regards.
