### ISSUE TITLE
crash bug, port ignoring

### ISSUE THREAD

**Issue by DOGSLV2** [zPirroZ3007/UUIDSpoofFix#2]
17.11 10:02:14 [Server] WARN [ViaVersion] Ignoring plugin channel in incoming REGISTER: legacy:fml|hs
17.11 10:02:14 [Connect] User thegamerslvfan1, IP **********
17.11 10:02:14 [Server] WARN [ViaVersion] Ignoring plugin channel in outgoing REGISTER: UUIDSpoofFix
17.11 10:02:14 [Server] WARN [ViaVersion] Ignoring plugin channel in outgoing REGISTER: RedisBungee
17.11 10:02:14 [Server] WARN [ViaVersion] Ignoring plugin channel in outgoing REGISTER: WECUI
screensshots: 
![image](https://user-images.githubusercontent.com/57896287/69045116-e1089280-09fe-11ea-9df2-61bd8ba042db.png)

players need relog in server

**Comment by DOGSLV2** [comment]
server runs 1.8 - 1.4.4

**Comment by zPirroZ3007** [comment]
Discontinued. Don't use this plugin, switch to more efficient solutions
