### ISSUE TITLE
Online Mode issue

### ISSUE THREAD

**Issue by ghost** [zPirroZ3007/UUIDSpoofFix#3]
If the online mode is on true (because the server is premium or because an attacker manages to set it that way by joining first with a premium uuid as soon as the server starts up) then said attacker can join with a non-premium nickname (a nickname that isn't yet registered) and the plugin will fail to find the right UUID for his/her nickname. This results in an exception spam in the console and allows the attacker to spoof his UUID at will. 

How to replicate this:

1) Set your online mode to true by joining your test server with a premium UUID (you can do it either with an online mode: true bungeecord server or with some modified client) 
2) Use CheatMine (or similar clients) to spoof your uuid and to set a non-premium nickname 
3) Join the server with any UUID you want

**Comment by zPirroZ3007** [comment]
Discontinued. Don't use this plugin, switch to more efficient solutions
